#!/usr/bin/env python3
"""Provision a Nyra ESPHome speaker with device-local private credentials."""
from __future__ import annotations

import argparse
import base64
import os
import re
import secrets
from pathlib import Path

SLUG_RE = re.compile(r"^nyra-[a-z0-9]+(?:-[a-z0-9]+)*$")


def _validate_device_name(device_name: str) -> None:
    if not SLUG_RE.fullmatch(device_name):
        raise ValueError(
            "device name must be lowercase and match nyra-<room>, using only letters, digits and hyphens"
        )


def _esphome_root_from_output(output: Path) -> Path | None:
    return output.parent.parent if output.parent.name == "devices" else None


def generate_private_values() -> tuple[str, str]:
    api_key = base64.b64encode(os.urandom(32)).decode("ascii")
    ota_password = secrets.token_hex(24)
    return api_key, ota_password


def create_private_secrets(device_name: str, esphome_root: Path) -> Path:
    """Create one gitignored private substitutions file for a speaker."""
    _validate_device_name(device_name)
    output = esphome_root / "device_secrets" / f"{device_name}.yaml"
    if output.exists():
        raise FileExistsError(output)

    api_key, ota_password = generate_private_values()
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(
        "# PRIVATE: generated locally; never commit this file.\n"
        f'api_encryption_key: "{api_key}"\n'
        f'ota_password: "{ota_password}"\n',
        encoding="utf-8",
    )
    try:
        output.chmod(0o600)
    except OSError:
        # Some mounted/config filesystems do not expose POSIX modes.
        pass
    return output


def create_device(device_name: str, friendly_name: str, output: Path) -> Path:
    _validate_device_name(device_name)
    if output.exists():
        raise FileExistsError(output)

    esphome_root = _esphome_root_from_output(output)
    wrapper: Path | None = None
    private_file: Path | None = None
    if esphome_root is not None:
        wrapper = esphome_root / output.name
        private_file = esphome_root / "device_secrets" / output.name
        for path in (wrapper, private_file):
            if path.exists():
                raise FileExistsError(path)

    content = f'''# Generated by tools/new-speaker.py. Keep only non-secret instance values here.
substitutions:
  device_name: {device_name}
  name: {device_name}
  friendly_name: "{friendly_name}"
  source_id: {device_name}
  posix_timezone: "CET-1CEST,M3.5.0,M10.5.0/3"
  volume_min: "0.4"
  volume_max: "0.8"
  hidden_ssid: "false"
  wakeword_model: "/config/esphome/wakewords/nira.json"
  nyra_assets_dir: "/config/esphome/assets"

packages:
  nyra: !include ../packages/nyra-speaker.yaml

api:
  encryption:
    key: "${{api_encryption_key}}"

ota:
  - platform: esphome
    password: "${{ota_password}}"
'''

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(content, encoding="utf-8")

    if esphome_root is not None:
        assert wrapper is not None
        assert private_file is not None
        create_private_secrets(device_name, esphome_root)
        wrapper.write_text(
            f"# Dashboard entrypoint for {device_name}.\n"
            f"substitutions: !include device_secrets/{device_name}.yaml\n"
            "packages:\n"
            f"  device: !include devices/{output.name}\n",
            encoding="utf-8",
        )

    return output


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("device_name", help="lowercase source/device id, e.g. nyra-mansarda")
    parser.add_argument("friendly_name", help='Home Assistant display name, e.g. "Nyra Mansarda"')
    parser.add_argument(
        "--output",
        type=Path,
        help="output YAML (default: esphome/devices/<device_name>.yaml)",
    )
    parser.add_argument(
        "--secrets-only",
        action="store_true",
        help="create only esphome/device_secrets/<device_name>.yaml; do not print secret values",
    )
    args = parser.parse_args()

    _validate_device_name(args.device_name)

    if args.secrets_only:
        path = create_private_secrets(args.device_name, Path("esphome"))
        print(f"Created private device secrets {path}")
        return 0

    output = args.output or Path("esphome/devices") / f"{args.device_name}.yaml"
    create_device(args.device_name, args.friendly_name, output)
    print(f"Created {output}")
    root = _esphome_root_from_output(output)
    if root is not None:
        print(f"Created {root / output.name}")
        print(f"Created private device secrets {root / 'device_secrets' / output.name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
